
-- 参考："イキタイ","サ活","サウナ飯","ターゲット","市区町村","施設名","施設タイプ","住所","TEL","HP","定休日","営業時間","料金","URL","CREATE_AT","緯度","経度"
-- サウナ施設マスタ
CREATE TABLE SAUNA_MASTER (
  FACILITY_ID TEXT PRIMARY KEY,
  ACILITY_NAME TEXT NOT NULL, 
  CITY TEXT NOT NULL, 
  ADDRESS TEXT NOT NULL,
  TEL TEXT,
  HP TEXT,
  FACILITY_TYPE_ID TEXT NOT NULL,
  REGULAR_HOLIDAY TEXT,
  BUSINESS_HOURS TEXT,
  PRICE TEXT,
  SAUNAIKITAI_URL TEXT NOT NULL,
  TARGET_ID TEXT NOT NULL,
  LATITUDE TEXT,
  LONGITUDE TEXT,
  CREATE_AT TEXT,
  UPDATE_AT TEXT
);
