-- 施設タイプマスタ
CREATE TABLE FACILITY_TYPE_MASTER (
  FACILITY_TYPE_ID TEXT PRIMARY KEY, 
  TYPE_NAME TEXT NOT NULL
);

-- データ追加
INSERT INTO FACILITY_TYPE_MASTER VALUES ('01', '銭湯（公衆浴場）');
INSERT INTO FACILITY_TYPE_MASTER VALUES ('02', '温浴施設（スーパー銭湯・サウナ・スパ施設）');
INSERT INTO FACILITY_TYPE_MASTER VALUES ('03', 'ラブホテル');
INSERT INTO FACILITY_TYPE_MASTER VALUES ('04', 'ホテル・旅館');
INSERT INTO FACILITY_TYPE_MASTER VALUES ('05', 'スポーツジム');
INSERT INTO FACILITY_TYPE_MASTER VALUES ('06', 'キャンプ場');
INSERT INTO FACILITY_TYPE_MASTER VALUES ('07', 'ゴルフ場');
INSERT INTO FACILITY_TYPE_MASTER VALUES ('08', 'その他');
INSERT INTO FACILITY_TYPE_MASTER VALUES ('09', '未設定');

