-- ターゲットマスタ
CREATE TABLE TARGET_MASTER (
  TARGET_ID TEXT PRIMARY KEY, 
  TARGET_NAME TEXT NOT NULL
);

-- データ追加
INSERT INTO TARGET_MASTER VALUES ('01', '男女');
INSERT INTO TARGET_MASTER VALUES ('02', '男性専用');
INSERT INTO TARGET_MASTER VALUES ('03', '女性専用');
INSERT INTO TARGET_MASTER VALUES ('04', '未設定');
